---
apache_mirror: http://apache.mirrors.tds.net
kafka_hosts: 192.168.0.6:9092
zookeeper_hosts: 192.168.0.6:2181
kafka_listen_address: 192.168.0.6
kafka_version: 0.8.1.1
run_mode: Deploy
skip_install: False

kafka_num_network_threads: 2
kafka_num_io_threads: 2
kafka_num_partitions: 2
kafka_port: 9092
kafka_socket_send_buffer_bytes: 1048576
kafka_socket_receive_buffer_bytes: 1048576
kafka_socket_request_max_bytes: 104857600
kafka_log_flush_interval_messages: 10000
kafka_log_flush_interval_ms: 1000
kafka_log_retention_bytes: 104857600  #100 M
kafka_log_retention_hours: 24
kafka_log_segment_bytes: "{{kafka_log_retention_bytes}}"
kafka_log_cleanup_interval_mins: 1
kafka_heap_opts: "-Xmx1G -Xms1G"
kafka_tarball_location: /root
kafka_tarball_name: "kafka_2.9.2-{{kafka_version}}.tgz"
monasca_wait_for_period: 30
monasca_log_level: WARN
zookeeper_connection_timeout_ms: 1000000

verify: True
